package com.sorteo.reportes.model;


import java.sql.ResultSet;

import com.core.SesionDatos;
import com.core.SuperModel;

public class mReporteVentas extends SuperModel {
	
	
	public ResultSet ventas(SesionDatos sesion) {
		/*
		String sql = "SELECT Asignaciones AS 'ASIGNS',SECTOR,NICHO,CLAVE,NOMBRE,REFBANCARIA AS 'REFERENCIA',TALONARIOS_DIG AS 'TALONARIOS',BOLETOS,Compradores, FC4"
				+ ", CASE WHEN (BOLETOS=Compradores) THEN 'completo' ELSE 'no' END 'Todos compradores capturados'"
				+ ", CASE WHEN (BOLETOS=Compradores AND Compradores=FC4) THEN 'completo' ELSE 'no' END 'Venta completa'"
				+ " FROM( SELECT * ,(SELECT COUNT(*) FROM SORTEOS_ASIGNACION_COLABORADORES SAC, NICHOS N    WHERE SAC.PK_NICHO=N.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'Asignaciones'"
				+ ",(SELECT TOP 1 S.SECTOR FROM SORTEOS_ASIGNACION_COLABORADORES SAC, SECTORES S WHERE SAC.PK_SECTOR=S.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'SECTOR'"
				+ " ,(SELECT TOP 1 N.NICHO FROM SORTEOS_ASIGNACION_COLABORADORES SAC, NICHOS N    WHERE SAC.PK_NICHO=N.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'NICHO'"
				+ " ,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B WHERE SCB.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1) AS 'BOLETOS'"
				+ " ,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, COMPRADORES COM WHERE SCB.PK_BOLETO=B.PK1 AND COM.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1) AS 'Compradores'"
				+ ",(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, COMPRADORES COM WHERE SCB.PK_BOLETO=B.PK1 AND COM.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1 AND B.RETORNADO=1) AS 'FC4'"
				+ " FROM( SELECT C.PK1,C.CLAVE ,CONCAT(C.NOMBRE,', ',C.APATERNO,' ',C.AMATERNO) AS 'NOMBRE' ,C.REFBANCARIA"
				+ " ,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_TALONARIOS SCT, TALONARIOS T WHERE SCT.PK_TALONARIO=T.PK1 AND SCT.PK_COLABORADOR=C.PK1 AND T.DIGITAL=1) AS 'TALONARIOS_DIG'"
				+ " FROM COLABORADORES C) AS  X  WHERE TALONARIOS_DIG>0) AS Y ORDER BY SECTOR,NICHO, CLAVE, NOMBRE";
				*/
		String sql
		= " SELECT Asignaciones AS 'ASIGNS',SECTOR,NICHO,CLAVE,NOMBRE,REFBANCARIA AS 'REFERENCIA',TALONARIOS_DIG AS 'TALONARIOS',BOLETOS,Compradores,VENDIDOS,FC4,MONTO,ABONO\n"
		+ " , CASE WHEN (BOLETOS=Compradores) THEN 'completo' ELSE 'no' END 'Todos compradores capturados'\n"
		+ " , CASE WHEN (BOLETOS=Compradores AND Compradores=FC4) THEN 'completo' ELSE 'no' END 'Venta completa'\n"
		+ " FROM(\n"
		+ " 	SELECT *\n"
		+ " 	,(SELECT COUNT(*) FROM SORTEOS_ASIGNACION_COLABORADORES SAC, NICHOS N    WHERE SAC.PK_NICHO=N.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'Asignaciones'\n"
		+ " 	,(SELECT TOP 1 S.SECTOR FROM SORTEOS_ASIGNACION_COLABORADORES SAC, SECTORES S WHERE SAC.PK_SECTOR=S.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'SECTOR'\n"
		+ " 	,(SELECT TOP 1 N.NICHO FROM SORTEOS_ASIGNACION_COLABORADORES SAC, NICHOS N    WHERE SAC.PK_NICHO=N.PK1 AND SAC.PK_COLABORADOR=X.PK1) AS 'NICHO'\n"
		
		+ " 	,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, TALONARIOS T                  WHERE SCB.PK_BOLETO=B.PK1 AND B.PK_TALONARIO=T.PK1 AND T.DIGITAL=1 AND SCB.PK_COLABORADOR=X.PK1) AS 'BOLETOS'\n"
		+ " 	,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, TALONARIOS T, COMPRADORES COM WHERE SCB.PK_BOLETO=B.PK1 AND B.PK_TALONARIO=T.PK1 AND T.DIGITAL=1 AND COM.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1) AS 'Compradores'\n"
	 	+ " 	,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, TALONARIOS T, COMPRADORES COM WHERE SCB.PK_BOLETO=B.PK1 AND B.PK_TALONARIO=T.PK1 AND T.DIGITAL=1 AND COM.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1 AND B.VENDIDO='V' AND B.RETORNADO=0) AS 'VENDIDOS'\n"
	 	+ " 	,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B, TALONARIOS T, COMPRADORES COM WHERE SCB.PK_BOLETO=B.PK1 AND B.PK_TALONARIO=T.PK1 AND T.DIGITAL=1 AND COM.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1 AND B.VENDIDO='V' AND B.RETORNADO=1) AS 'FC4'\n"
		
	 	+ " 	,(SELECT SUM(B.COSTO) FROM SORTEOS_COLABORADORES_BOLETOS SCB, BOLETOS B WHERE SCB.PK_BOLETO=B.PK1 AND SCB.PK_COLABORADOR=X.PK1)*X.COMISION AS 'MONTO'\n"
		+ " 	FROM(\n"
		+ " 		SELECT\n" 
		+ " 		C.PK1,C.CLAVE\n"
		+ " 		,CONCAT(C.NOMBRE,', ',C.APATERNO,' ',C.AMATERNO) AS 'NOMBRE'\n"
		+ " 		,C.REFBANCARIA,COMISION,ABONO\n"
		+ " 		,(SELECT COUNT(*) FROM SORTEOS_COLABORADORES_TALONARIOS SCT, TALONARIOS T WHERE SCT.PK_TALONARIO=T.PK1 AND SCT.PK_COLABORADOR=C.PK1 AND T.DIGITAL=1) AS 'TALONARIOS_DIG'\n"
		+ " 		FROM COLABORADORES C WHERE PK_SORTEO=" + sesion.pkSorteo + "\n"
		+ " 	) AS  X\n"
		+ " 	WHERE TALONARIOS_DIG>0\n"
		+ " ) AS Y\n"
		+ " ORDER BY SECTOR,NICHO, CLAVE, NOMBRE\n";

		System.out.println("model: reporte excel: " + sql);

		ResultSet rs = db.getDatos(sql);
		return rs;
	}	
	
	
	
	public ResultSet ventas2(SesionDatos sesion) {		

		ResultSet rs =  db.execStoreProcedure("sp_ObtenerVentas");	
		//System.out.println("model: reporte excel: " + sql);
		return rs;
	}	
	
	public ResultSet export_retornoTal(SesionDatos sesion) {		
		

		String sql = " SELECT  * FROM  ( SELECT  S.PK_TALONARIO,T.VENDIDO,T.ABONO,T.MONTO, T.FOLIO, T.FORMATO, "
				+ " (SELECT  COUNT(B.PK1) AS 'BRETORNADOS' FROM BOLETOS B WHERE B.TALONARIO = S.PK_TALONARIO AND B.SORTEO = " + sesion.pkSorteo + " AND B.VENDIDO = 'V' AND B.RETORNADO = 1 ) AS 'BRETORNADOS', "
				+ " (select TOP 1 PK_SECTOR  from SORTEOS_SECTORES_TALONARIOS  where PK_TALONARIO = S.PK_TALONARIO) AS 'PK_SECTOR',"
				+ " (select TOP 1 SECTOR FROM SECTORES  WHERE PK1=(select TOP 1 PK_SECTOR  from SORTEOS_SECTORES_BOLETOS  where PK_TALONARIO = S.PK_TALONARIO)) AS 'SECTOR',"
				+ " (select TOP 1 PK_NICHO from SORTEOS_NICHOS_TALONARIOS where PK_TALONARIO = S.PK_TALONARIO) AS 'PK_NICHO',"
				+ " (select TOP 1 NICHO  FROM NICHOS  WHERE PK1=(select TOP 1 PK_NICHO from SORTEOS_NICHOS_TALONARIOS where PK_TALONARIO = S.PK_TALONARIO)) AS 'NICHO',"
				+ " (select TOP 1 PK_COLABORADOR from SORTEOS_COLABORADORES_TALONARIOS  where PK_TALONARIO = S.PK_TALONARIO) AS 'PK_COLABORADOR', "
				+ " (select TOP 1 NOMBRE+' '+APATERNO  FROM COLABORADORES WHERE PK1=(select TOP 1 PK_COLABORADOR from SORTEOS_COLABORADORES_TALONARIOS  where PK_TALONARIO = S.PK_TALONARIO)) AS 'COLABORADOR'"
				+ " FROM SORTEOS_TALONARIOS S, TALONARIOS T WHERE S.PK_TALONARIO = T.PK1 AND S.PK_SORTEO = " + sesion.pkSorteo + " AND T.VENDIDO='V' )"
				+ " AS RowConstrainedResult  WHERE   RowConstrainedResult.BRETORNADOS = 11";
	
		
		//System.out.println("model export_retornoTal: " + sql);
		ResultSet rs = db.getDatos(sql);
		return rs;
	}	
	
	
	

}
